Code reorganization to facilitate planned `Added/Changed` extension`
JoJoJet/bevy-trait-query pull request #29
Opened 2022-12-10 16:54 UTC by bzm3r

`lib.rs` is becoming quite unwieldy with the new extensions planned to `Added/Changed`: for instance, there will be new `WorldQuery` adapters, `ReadTraits` iterators, and new `WriteTraits` iterators. In order to make the file easier to navigate, and thereby mitigate the risk of errors, I think it will be useful to reorganize the code

2022-12-10 18:06 UTC, JoJoJet requested changes
These files are way too small. I don't see much benefit in separating `multiple_read` and `multiple_write` from `all` -- same with `singular_*` and `one`.

2022-12-10 20:54 UTC, bzm3r commented
@JoJoJet ah, `one` and `all` will be the files that will grow the most in the upcoming changes. `multiple_read` and `multiple_write` will also see significant growth. 

What I can do is keep this PR open, and work on the added/changed stuff. Once that PR is up, you'll have more information as to how things ought to be organized?

2022-12-10 22:24 UTC, bzm3r commented
Okay, because it seemed that I can keep the `singular_*` files small even after change detection, I've collapsed them into `one`

2022-12-10 23:11 UTC, JoJoJet commented
I will leave the decision up to you, but IMO it's fine to just merge those files. `all.rs` will be quite long, but that's okay.

2022-12-11 00:50 UTC, JoJoJet requested changes

2022-12-11 00:50 UTC, JoJoJet commented on src/lib.rs
> +//! you can use the filter [`One`](One). This has significantly better performance than iterating
```suggestion
//! you can use the filter [`One`](crate::One). This has significantly better performance than iterating
```

Due to a limitation with the `cargo-rdme` tool, all doc links in the README must start with `crate::`.

2022-12-11 00:50 UTC, JoJoJet commented on src/lib.rs
> +//!
I don't think this belongs here?

2022-12-11 02:19 UTC, JoJoJet commented
So, apparently cargo-rdme doesn't like re-exports, so that doc comment on line 167 of lib.rs needs to be `crate::one::One`

2022-12-12 15:52 UTC, JoJoJet commented
Github won't let me push to this branch, so I'm just going to go ahead and merge this, then apply my nitpicks in a follow-up PR.

2022-12-12 15:53 UTC, JoJoJet approved these changes

2022-12-12 15:53 UTC, merged